name: epub_renderer
description: A superset of the epub_parser that renders the epubs through unopinionated widgets
version: 1.0.0
author: Olympus Software
homepage: https://olmps.co

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Webview support
  webview_flutter: ^0.3.20+2

  # flutter_inappwebview:

  # Plugin for playing audio files
  just_audio: ^0.4.4


  epub_parser:
    path: ../epub_parser

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocks for unit testing
  mockito: 4.1.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: EpubRendererPlugin