name: epub_reader
description: A simple Epub Reader designed for mobile Flutter applications
version: 1.0.0
author: Olympus Software
homepage: https://olmps.co

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Helper for finding common directories on all mobile systems
  path_provider: 1.6.11
  
  # Create and extracted ZIP files 
  flutter_archive: ^1.0.2

  # XML files parser
  xml: ^3.6.1

  # Webview support
  webview_flutter: ^0.3.20+2
  
  # Plugin for playing audio files
  just_audio: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocks for unit testing
  mockito: 4.1.1